### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by arne-cl** [yeraydiazdiaz/wait_for_it.py#2]
Dear Yeray,

when I try to run the script, I get this error:
```
python wait_for_it.py http://localhost:8080
Traceback (most recent call last):
  File "wait_for_it.py", line 106, in <module>
    main()
  File "wait_for_it.py", line 93, in main
    args.service_url, timeout=args.timeout, retry_interval=args.retry
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by yeraydiazdiaz** [comment]
Fixed via #3
